#!/usr/bin/env python3
"""Generate sound effect data for Floppy Bird game.

Outputs main/flappy_sounds.h with C arrays for flap, score, and death sounds.
No external dependencies - uses only Python standard library.
"""

import math

SAMPLE_RATE = 44100


def generate_flap():
    """Sine sweep 200->500Hz, 80ms, fade-out envelope."""
    duration = 0.08
    samples = int(SAMPLE_RATE * duration)
    data = []
    for i in range(samples):
        t = i / SAMPLE_RATE
        progress = i / samples
        # Frequency sweep from 200 to 500 Hz
        freq = 200 + 300 * progress
        # Instantaneous phase using integral of frequency
        phase = 2 * math.pi * (200 * t + 300 / (2 * duration) * t * t)
        # Fade-out envelope
        envelope = 1.0 - progress
        value = math.sin(phase) * envelope * 0.8
        data.append(max(-1.0, min(1.0, value)))
    return data


def generate_score():
    """Two-tone ding: 880Hz 60ms + 1320Hz 60ms."""
    duration_each = 0.06
    samples_each = int(SAMPLE_RATE * duration_each)
    data = []
    # First tone: 880 Hz
    for i in range(samples_each):
        t = i / SAMPLE_RATE
        envelope = 1.0 - (i / samples_each) * 0.3
        value = math.sin(2 * math.pi * 880 * t) * envelope * 0.8
        data.append(max(-1.0, min(1.0, value)))
    # Second tone: 1320 Hz
    for i in range(samples_each):
        t = i / SAMPLE_RATE
        envelope = 1.0 - (i / samples_each)
        value = math.sin(2 * math.pi * 1320 * t) * envelope * 0.8
        data.append(max(-1.0, min(1.0, value)))
    return data


def generate_death():
    """Triangle wave sweep 400->100Hz, 300ms, decay envelope."""
    duration = 0.3
    samples = int(SAMPLE_RATE * duration)
    data = []
    phase = 0
    for i in range(samples):
        progress = i / samples
        freq = 400 - 300 * progress
        envelope = 1.0 - progress
        # Accumulate phase
        phase += freq / SAMPLE_RATE
        # Triangle wave from phase
        tri = 2 * abs(2 * (phase % 1.0) - 1) - 1
        value = tri * envelope * 0.8
        data.append(max(-1.0, min(1.0, value)))
    return data


def float_to_int16(samples):
    """Convert float samples [-1.0, 1.0] to int16."""
    return [max(-32767, min(32767, int(s * 32767))) for s in samples]


def write_header(filename, sounds):
    """Write C header file with sound data arrays."""
    with open(filename, 'w') as f:
        f.write("// Auto-generated sound effects for Floppy Bird\n")
        f.write("// Generated by generate_sounds.py - 44.1kHz, 16-bit PCM\n\n")
        f.write("#ifndef FLAPPY_SOUNDS_H\n")
        f.write("#define FLAPPY_SOUNDS_H\n\n")
        f.write("#include <stdint.h>\n\n")

        names = ["flap_sound", "score_sound", "die_sound"]
        lengths = []

        for name, float_samples in zip(names, sounds):
            int_samples = float_to_int16(float_samples)
            lengths.append(len(int_samples))
            f.write(f"const int16_t {name}[{len(int_samples)}] = {{\n")
            for i in range(0, len(int_samples), 12):
                chunk = int_samples[i:i+12]
                line = ", ".join(f"{s:6d}" for s in chunk)
                f.write(f"    {line},\n")
            f.write("};\n\n")

        f.write(f"const int16_t* const flappy_samples[3] = {{ {', '.join(names)} }};\n")
        f.write(f"const uint32_t flappy_lengths[3] = {{ {', '.join(str(l) for l in lengths)} }};\n\n")
        f.write("#endif // FLAPPY_SOUNDS_H\n")


if __name__ == "__main__":
    flap = generate_flap()
    score = generate_score()
    death = generate_death()
    write_header("main/flappy_sounds.h", [flap, score, death])
    print(f"Generated main/flappy_sounds.h")
    print(f"  Flap:  {len(flap)} samples ({len(flap)/SAMPLE_RATE*1000:.0f}ms)")
    print(f"  Score: {len(score)} samples ({len(score)/SAMPLE_RATE*1000:.0f}ms)")
    print(f"  Death: {len(death)} samples ({len(death)/SAMPLE_RATE*1000:.0f}ms)")
